# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Yilin Mo
description:      'I am an Assistant Professor at Nanyang Technologicial University, Singapore.'
url:              http://yilinmo.github.io
baseurl:          /

author:
  name:           'Yilin Mo'
email:            ylmo@ntu.edu.sg

paginate:         1
paginate_path:    "/blog/page:num"

# Custom vars
