# Dependencies
highlighter:      rouge

# Setup
title:            Yilin Mo
tagline:          'Research and Stuff'
description:      'I am an Associate Professor at Tsinghua University, China.'
url:              http://yilinmo.github.io
baseurl:          ''
cover_image: /public/zion.png

author:
name:           'Yilin Mo'
email:            ylmo@tsinghua.edu.cn

paginate:         5
paginate_path:    "/notes/page:num"

# List of Pages

pages_list:
  - name: Research
    loc: /research.html
  - name: Teaching
    loc: /teaching.html
  - name: Publication
    loc: /publication.html
  - name: Notes
    loc: /notes

# Chinese Support
# Must change the cn_font_family and cn_css
# Right now it only contains the chinese characters of my name!!!
# To select font, go to: http://www.youziku.com/Home/FontSelect
# or you can remove the title_cn attribute

#title_cn: (莫一林)
cn_font_family: minijianxixingkai351678
cn_css: http://www.youziku.com/webfont/CSS/15f8f8252e25142e32cc295517e8a5f0

# Google font server
google_font_server: fonts.useso.com # 360 server for mainland China readers.

# In case you do not care about Chinese readers, use the default google server
# google_font_server: fonts.googleapis.com

plugins: 
        - jekyll-paginate
