# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks

# Setup
title:            Yilin Mo
description:      'I am an Assistant Professor at Nanyang Technologicial University, Singapore.'
url:              http://yilinmo.github.io
baseurl:          /

author:
  name:           'Yilin Mo'
email:            ylmo@ntu.edu.sg

paginate:         5
paginate_path:    "/notes/page:num"
# Custom vars
