#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_EXPORT HTML
---
layout: page
title: ! 'Convex Optimization Based State Estimation against Sparse Integrity Attacks'
comments: true
---
#+END_EXPORT
--------------------------------
*Duo Han, Yilin Mo and Lihua Xie*

/American Control Conference/, 2016 

Link to the [[../../../public/papers/acc16-1.pdf][paper]]

If you want to leave any comments, you can annotate the [[../../../pdfviewer/viewer/web/viewer.html?file=%2Fpublic%2Fpapers%2Facc16-1.pdf][pdf]]. I will try to be responsive. You can also annotate this page or leave comments below. 

** Abstract
We consider the problem of robust estimation in presence of integrity attacks. There are $m$ sensors monitoring the state and $p$ of them are under attack. The malicious measurements collected by the compromised sensors can be manipulated arbitrarily by the attacker. The classical estimators such as the least squares estimator may not provide a reliable estimate under the so-called $(p,m)$-sparse attack. In this work, we are not restricting our efforts in studying whether any specific estimator is resilient to the attack or not, but instead we aim to present some generic sufficient and necessary conditions for robustness by considering a general class of convex optimization estimators. The sufficient and necessary conditions are shown to be tight, with a trivial gap. We further specialize our result to scalar sensor measurements case.
