#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_EXPORT HTML
---
comments: true
layout: page
title: Convex Optimization Based State Estimation against Sparse Integrity Attacks
---
#+END_EXPORT
--------------------------------
*Duo Han, Yilin Mo and Lihua Xie*

/Automatica/, In Review

Link to the [[../../../public/papers/automatica16.pdf][paper]]

If you want to leave any comments, you can annotate the [[../../../pdfviewer/viewer/web/viewer.html?file=%2Fpublic%2Fpapers%2Fautomatica16.pdf][pdf]]. I will try to be responsive. You can also annotate this page or leave comments below. 

** Abstract

We consider the problem of resilient state estimation in the presence of integrity attacks. There are $m$ sensors monitoring the state and $p$ of them are under attack. The sensory data collected by the compromised sensors can be manipulated arbitrarily by the attacker. The classical estimators such as the least squares estimator may not provide a reliable estimate under the so-called $(p,m)$-sparse attack. In this work, we are not restricting our efforts in studying whether any specific estimator is resilient to the attack or not, but instead we aim to present some generic sufficient and necessary conditions for resilience by considering a general class of convex optimization based estimators. The sufficient and necessary conditions are shown to be tight, with a trivial gap. We further specialize our result to scalar sensor measurements case. Experimental results tested on the IEEE 14-bus test system validate the theoretical analysis.
