#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_EXPORT HTML
---
layout: page
title: ! 'Secure Dynamic State Estimation via Local Estimators'
comments: true
---
#+END_EXPORT
--------------------------------
*Yilin Mo and Emanuele Garone*

/IEEE Conference on Decision and Control/, 2016

Link to the [[../../../public/papers/cdc16-1.pdf][paper]]

If you want to leave any comments, you can annotate the [[../../../pdfviewer/viewer/web/viewer.html?file=%2Fpublic%2Fpapers%2Fcdc16-1.pdf][pdf]]. I will try to be responsive. You can also annotate this page or leave comments below. 

** Abstract
We consider the problem of estimating the state of a linear time-invariant Gaussian system using $m$ sensors, where a subset of the sensors can potentially be compromised by an adversary. We prove that under mild assumptions, we can decompose the optimal Kalman estimate as a weighted sum of local state estimates, each of which is derived using only the measurements from a single sensor. We then propose a convex optimization based approach, instead of the weighted sum approach, to combine the local estimate into a more secure state estimate. Our proposed estimator coincides with the Kalman estimator with certain probability when all sensors are benign and is stable when less than half of the sensors are compromised. Numerical simulations are provided to illustrate the performance of the proposed state estimation scheme.
