#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_EXPORT HTML
---
layout: page
title: Local Decompostion of Kalman Filters and Its Application for Secure State Estimation
---
#+END_EXPORT
--------------------------------

*Xinghua Liu, Yilin Mo and Emanuele Garone*

/IEEE Trans. on Automatic Control/, Submitted

Link to the [[../../../public/papers/tac18localkf.pdf][paper]]

** Abstract

 This technical note is concerned with the secure state estimation problem of a linear discrete-time Gaussian system in the presence of sparse integrity attacks. $m$ sensors are deployed to monitor the state and $p$ of them can potentially be compromised by an adversary, whose data can be arbitrarily manipulated by the attacker. We show that the optimal Kalman estimate can be decomposed as a weighted sum of local state estimates. Based on these local estimates, we propose a convex optimization based approach to generate a more secure state estimate. It is proved that our proposed estimator coincides with the Kalman estimator with a certain probability when all sensors are benign. Besides, we establish a sufficient condition under which the proposed estimator is stable against the $(p,m)$-sparse attack. A numerical example is provided to validate the secure state estimation scheme.
