#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_EXPORT HTML
---
comments: true
layout: page
title: On Infinite-Horizon Sensor Scheduling
---
#+END_EXPORT
--------------------------------

*Yilin Mo, Emanuele Garone and Bruno Sinopoli*

/System & Control Letters/, May 2014, Volume 67, Pages 65-70,

Link to the [[../../../public/papers/optimalisperiodic.pdf][paper]]

If you want to leave any comments, you can annotate the [[../../../pdfviewer/viewer/web/viewer.html?file=%2Fpublic%2Fpapers%2Foptimalisperiodic.pdf][pdf]]. I will try to be responsive. You can also annotate this page or leave comments below. 

** Abstract

In this paper we consider the problem of infinite-horizon sensor scheduling for estimation in linear Gaussian systems. Due to possible channel capacity, energy budget or topological constraints, it is assumed that at each time step only a subset of the available sensors can be selected to send their observations to the fusion center, where the state of the system is estimated by means of a Kalman filter. Several important properties of the infinite-horizon schedules will be presented in this paper. In particular, we prove that the infinite-horizon average estimation error and the boundedness of a schedule are independent of the initial covariance matrix. We further provide a constructive proof that any feasible schedule with finite average estimation error can be arbitrarily approximated by a bounded periodic schedule. We later generalized our result to lossy networks. These theoretical results provide valuable insights and guidelines for the design of computationally efficient sensor scheduling policies.
