#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_EXPORT HTML
---
layout: page
title: On Optimal Partial Broadcasting of Wireless Sensor Networks for Kalman Filtering
---
#+END_EXPORT
--------------------------------

*Qing-Shan Jia, Ling Shi, Yilin Mo and Bruno Sinopoli*
 
/IEEE Transactions on Automatic Control/, Mar 2012, Volum 57, Issue 3, Pages 715-721

State estimation using wireless sensor networks (WSNs) is an important technique in many commercial and military applications, in which a group of (nonidentical) sensors take noisy observations of system state and send back to a fusion center through wireless broadcasting for state estimation. In order to minimize the terminal estimation error covariance at the fusion center, a partial broadcasting policy should tell which sensors to broadcast at each stage. The limited battery allows each sensor to broadcast only a few times. The limited wireless communication bandwidth allows only a few sensors to broadcast at the same time. Due to these couplings, the optimal partial broadcasting policy is not clear in general. Despite the abundant applications of partial broadcasting policies, theoretical analysis is rare. In this technical note, we provide a first study on the properties of optimal partial broadcasting policies. When there is no packet drop, a good-sensor-late-broadcast (GSLB) rule is shown to perform optimally for both the scalar system and the vector system. When packet drops with positive probability, situations in which the GSLB rule may or may not perform optimally are analyzed. Under different dropping rates, the GSLB rule is compared with several other policies through simulations.
