#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_EXPORT HTML
---
comments: true
layout: page
title: Stochastic Sensor Scheduling for Energy Constrained Estimation in Multi-Hop Wireless Sensor Networks
---
#+END_EXPORT
--------------------------------

*Yilin Mo, Emanuele Garone, Alessandro Casavola and Bruno Sinopoli*

/IEEE Transactions on Automatic Control/, Oct 2011, Volume 56, Issue 10, Pages 2489-2495

Link to the [[../../../public/papers/tac11sensor.pdf][paper]]

If you want to leave any comments, you can annotate the [[../../../pdfviewer/viewer/web/viewer.html?file=%2Fpublic%2Fpapers%2Ftac11sensor.pdf][pdf]]. I will try to be responsive. You can also annotate this page or leave comments below. 

** Abstract
Wireless Sensor Networks (WSNs) enable a wealth of new applications where remote estimation is essential. Individual sensors simultaneously sense a dynamic process and transmit measured information over a shared channel to a central fusion center. The fusion center computes an estimate of the process state by means of a Kalman filter. In this technical note we assume that the WSN admits a tree topology with one fusion center at the root. At each time step only a subset of sensors can be selected to transmit observations to the fusion center due to a limited energy budget. We propose a stochastic sensor selection algorithm that randomly selects a subset of sensors according to a certain probability distribution, which is opportunely designed to minimize the asymptotic expected covariance matrix of the estimation error. We show that the optimal stochastic sensor selection problem can be relaxed into a convex optimization problem and thus efficiently solved. We also provide a possible implementation of our algorithm which does not introduce any communication overhead. The technical note ends with some numerical examples that show the effectiveness of the proposed approach.

** Comments

The Problem 4 can be solved directly via semidefinite programming. As a result, Problem 5 is no longer needed. For details, please see my [[http://yilinmo.github.io/properties-of-dare/#outline-container-sec-3][notes]].
