#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_EXPORT HTML
---
comments: true
layout: page
title: Privacy Preserving Average Consensus
---
#+END_EXPORT
--------------------------------
*Yilin Mo and Richard M. Murray*

/IEEE Transactions on Automatic Control/, Accepted

Link to the [[../../../public/papers/tac2014privacy.pdf][paper]]

If you want to leave any comments, you can annotate the [[../../../pdfviewer/viewer/web/viewer.html?file=%2Fpublic%2Fpapers%2Ftac2014privacy.pdf][pdf]]. I will try to be responsive. You can also annotate this page or leave comments below. 

** Abstract
Average consensus is a widely used algorithm for distributed computing and control, where all the agents in the network constantly communicate and update their states in order to achieve an agreement. This approach could result in an undesirable disclosure of information on the initial state of an agent to the other agents. In this paper, we propose a privacy preserving average consensus algorithm to guarantee the privacy of the initial state and asymptotic consensus on the exact average of the initial values, by adding and subtracting random noises to the consensus process. We characterize the mean square convergence rate of our consensus algorithm and derive the covariance matrix of the maximum likelihood estimate on the initial state. Moreover, we prove that our proposed algorithm is optimal in the sense that it does not disclose any information more than necessary to achieve the average consensus. A numerical example is provided to illustrate the effectiveness of the proposed design.

** Acknowledgement
The authors would like to thank Tianyi Bai(tbai@clipper.ens.fr) and Guoda Tian for carefully proofreading the paper.
