#+OPTIONS: H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_EXPORT HTML
---
comments: true
layout: page
title: On the Performance Degradation of Cyber-Physical Systems under Stealthy Integrity Attacks
---
#+END_EXPORT
--------------------------------
*Yilin Mo and Bruno Sinopoli*

/IEEE Transactions on Automatic Control/, Accepted

Link to the [[../../../public/papers/tac-12-integrity.pdf][paper]]

If you want to leave any comments, you can annotate the [[../../../pdfviewer/viewer/web/viewer.html?file=%2Fpublic%2Fpapers%2Ftac-12-integrity.pdf][pdf]]. I will try to be responsive. You can also annotate this page or leave comments below. 

** Abstract

This paper analyzes the effect of stealthy integrity attacks on Cyber-Physical Systems, which is modeled as a Stochastic Linear Time-Invariant (LTI) system equipped with a linear filter, a linear feedback controller and a $\chi^2$ failure detector. An attacker wishes to induce perturbation in the control loop by compromising a subset of the sensors and injecting an exogenous control input, without incurring detection from an anomaly detector. We show how the problem can be modeled, from the attacker's standpoint, as a constrained control problem and that the characterization of the maximum perturbation can be posed as reachable set computation, which we solve using ellipsoidal calculus. 

** Simulation Code

The code is written in Matlab R2009b (7.9.0.529).
- [[../../../public/code/tac-12-integrity/plotellipsoid.m][plotellipsoid.m]]
- [[../../../public/code/tac-12-integrity/position.m][position.m]]
- [[../../../public/code/tac-12-integrity/velocity.m][velocity.m]]
