#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_EXPORT HTML
---
comments: true
layout: page
title: Secure Estimation in the Presence of Integrity Attacks
---
#+END_EXPORT
--------------------------------

*Yilin Mo and Bruno Sinopoli*

/IEEE Transactions on Automatic Control/, Apr 2015, Volume 60, Issue 4, Pages 1145-1151

Link to the [[../../../public/papers/j13secureestimation.pdf][paper]]

If you want to leave any comments, you can annotate the [[../../../pdfviewer/viewer/web/viewer.html?file=%2Fpublic%2Fpapers%2Fj13secureestimation.pdf][pdf]]. I will try to be responsive. You can also annotate this page or leave comments below. 

** Abstract
We consider the estimation of a scalar state based on m measurements that can be potentially manipulated by an adversary. The attacker is assumed to have full knowledge about the true value of the state to be estimated and about the value of all the measurements. However, the attacker has limited resources and can only manipulate up to $l$ of the $m$ measurements. The problem is formulated as a minimax optimization, where one seeks to construct an optimal estimator that minimizes the "worst-case" expected cost against all possible manipulations by the attacker. We show that if the attacker can manipulate at least half the measurements ($l \geq m/2$), then the optimal worst-case estimator should ignore all measurements and be based solely on the a-priori information. We provide the explicit form of the optimal estimator when the attacker can manipulate less than half the measurements ($l < m/2$), which is based on $m\choose{2l}$ local estimators. We further prove that such an estimator can be reduced into simpler forms for two special cases, i.e., either the estimator is symmetric and monotone or $m = 2l + 1$. Finally we apply the proposed methodology in the case of Gaussian measurements.
