#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_EXPORT HTML
---
layout: page
title: Detection in Adversarial Environments
---
#+END_EXPORT
--------------------------------

*Kyriakos Vamvoudakis, Jo\atilde{}o Hespanha, Bruno Sinopoli and Yilin Mo*

/IEEE Transactions on Automatic Control, Special Issue on Control of Cyber-Physical Systems/, Dec 2014, Volume 59, Issue 12, Special Issue S1, Pages 3209-3223

We propose new game theoretic approaches to estimate a binary random variable based on sensor measurements that may have been corrupted by a cyber-attacker. The estimation problem is formulated as a zero-sum partial information game in which a detector attempts to minimize the probability of an estimation error and an attacker attempts to maximize this probability. While this problem can be solved exactly by reducing it to the computation of the value of a matrix, this approach is computationally feasible only for a small number of sensors. The two key results of this paper provide complementary computationally efficient solutions to the construction of the optimal detector. The first result provides an explicit formula for the optimal detector but it is only valid when the number of sensors is roughly smaller than two over the probability of sensor errors. In contrast, the detector provided by the second result is valid for an arbitrary number of sensor. While it may result in a probability of estimation error that is above the minimum achievable, we show that this error is small when the number of sensors is large, which is precisely the case for which the first result does not apply.
