#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_EXPORT HTML
---
comments: true
layout: page
title: Detecting Integrity Attacks on SCADA Systems 
---
#+END_EXPORT
--------------------------------

*Yilin Mo, Rohan Chabukswar and Bruno Sinopoli*

/IEEE Transactions on Control System Technology/, Jul 2014, Volume 22, Issue 4, 1396-1407

Link to the [[../../../public/papers/j12replay.pdf][paper]]

If you want to leave any comments, you can annotate the [[../../../pdfviewer/viewer/web/viewer.html?file=%2Fpublic%2Fpapers%2Fj12replay.pdf][pdf]]. I will try to be responsive. You can also annotate this page or leave comments below. 

** Abstract
Ensuring security of systems based on supervisory control and data acquisition is a major challenge. The goal of this paper is to develop the model-based techniques capable of detecting integrity attacks on the sensors of a control system. In this paper, the effect of integrity attacks on the control systems is analyzed and countermeasures capable of exposing such attacks are proposed. The main contributions of this paper, beyond the novelty of the problem formulation, lies in enumerating the conditions of the feasibility of the replay attack, and suggesting countermeasures that optimize the probability of detection by conceding control performance. The methodologies are shown and the theoretical results are validated using several sets of simulations.
